### ISSUE TITLE
@refactor-wifi bugs!

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/esp-rfid#20]
This is the behavior:

**- esp-rfid started with wifi on:** works correctly

**-  esp-rfid started with wifi off:** it does not read any cards and hangs in "......[ INFO ] WiFi STA Disconnected" until wifi comes back (its reconnects correctly) see bottom log 

`[ INFO ] ESP RFID v1.3.5
Flash real id:   00164068
Flash real size: 4194304

Flash ide  size: 4194304
Flash ide speed: 40000000
Flash ide mode:  DIO
Flash Chip configuration ok.

[ INFO ] Config file found
[ INFO ] Trying to setup RFID Hardware
[ INFO ] Configuration done.
[ INFO ] Trying to setup MQTT
[ INFO ] Trying to connect WiFi: Ares-plus1
[ INFO ] WiFi BSSID: 82:180:65:97:232:104
[ INFO ] BSSID locked
.....[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
.....[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected`

**- esp-rfid started with wifi active and then turns off:** it correctly reads the cards that do not have access (with correct feedback) but when you pass an enabled card it opens but the beeper does not turn off for all the time that elapses from "[INFO ] wifi | Enabling WiFi | " up to "[WARN] Couldn't connect in time"  during all cyclic periods it does not read any cards

`INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] PICC's UID: 381ED05E
 = known PICC
[ INFO ] User Name: utente normale does not have access
[ INFO ] Read timeout or clean after read
LED waiting OFF
Beeper ON
Beeper OFF
Beeper ON
Beeper OFF
Beeper ON
Beeper OFF
[ INFO ] PICC's UID: 381ED05E
 = known PICC
[ INFO ] User Name: utente normale does not have access
[ INFO ] Read timeout or clean after read
LED waiting OFF
Beeper ON
[ INFO ] WiFi STA Disconnected
Beeper OFF
Beeper ON
Beeper OFF
Beeper ON
Beeper OFF
[ INFO ] PICC's UID: 345F1CF5
[ WARN ] rfid | Unknown rfid tag is scanned | 345f1cf5 34
[ INFO ] Read timeout or clean after read
LED waiting OFF
Beeper ON
Beeper OFF
Beeper ON
Beeper OFF
Beeper ON
Beeper OFF
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] PICC's UID: D2023B04
 = known PICC
[ INFO ] User Name: Giuseppe Treccarichi has admin access, enable wifi
Beeper ON
[ INFO ] Read timeout or clean after read
LED waiting OFF
mili : 232315
activating relay 0 now
mili : 232354
activating relay 1 now
mili : 232394
activating relay 2 now
[ INFO ] wifi | Enabling WiFi | 
[ INFO ] Trying to connect WiFi: Ares-plus1
[ INFO ] WiFi BSSID: 82:180:65:97:232:104
[ INFO ] BSSID locked
.....[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
.....[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
......[ INFO ] WiFi STA Disconnected
..
[ WARN ] Couldn't connect in time
Beeper OFF
262586
232426
1000
0
deactivate relay after this
mili : 262637
262586
232426
3000
0
deactivate relay after this
mili : 262640
262586
232426
300
0
deactivate relay after this
mili : 262711
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected
[ INFO ] WiFi STA Disconnected`

**Comment by matjack1** [comment]
Secondo me questo ora è a posto sulla dev di esp-rfid. Chiudo ma se serve riapri!
