### ISSUE TITLE
Rc522 card reading UI has no pop-up window and scanning is abnormal.

### ISSUE THREAD

**Issue by vvvyky** [FablabTorino/esp-rfid#22]
The new window does not pop up in the development version rc522 card reading, and the scanning is abnormal.

![微信图片_20220520190818](https://user-images.githubusercontent.com/38814385/169516885-1e3d6681-e3e3-4ea8-9e44-9a1ab30cecfb.png)

**Comment by matjack1** [comment]
let's keep the discussion on the main repo: https://github.com/esprfid/esp-rfid/issues/506

I'm going to get back to you soon, sorry I've been quite busy lately
