### ISSUE TITLE
Implement log rotation

### ISSUE THREAD

**Issue by matjack1** [FablabTorino/esp-rfid#23]
It's fake now

**Comment by giutrec** [comment]
@matjack1 visto che questo repository è deprecato avevo aperto una issue su quello del door-opener (anche se è riferita all'esp-rfid da sviluppare sul repo ufficiale)
https://github.com/FablabTorino/door-opener/issues/34

**Comment by giutrec** [comment]
quelle che riguardano le nostre implementazioni sono tutte sul repo door-opener
Questo repo qui vorrei proprio segnarlo come deprecato
