### ISSUE TITLE
NEW FEATURES (MAYBE)

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/esp-rfid#5]
This is a list of features that may be worth adding

- [x] Configurable access times 
- [x] Define the bits of the wiegand keypad from the web interface (there are 4 and 8 bit keypads) ---- AUTOMATIC DISCOVER 4 and 8 bit
- [x] Disable fallbackmode on web interface
- [x] Rewrite the function to reconnect without reboot in case of lack of wifi signal

**Comment by giutrec** [comment]
- [x] rewrite interely wifi function

**Comment by matjack1** [comment]
tutto fatto!
